#include<stdio.h>
#include<conio.h>
void main()
{
	int a,b,add,sub,mul,div;
	clrscr();
	printf("enter a and b:");
	scanf("%d%d",&a,&b);
	add=a+b;
	sub=a-b;
	mul=a*b;
	div=a/b;
	printf("\n the addition of a and b is = %d",add);
	printf("\n the subtraction of a and b is = %d",sub);
	printf("\n the multipication of a and b is= %d",mul);
	printf("\n the division of a and b is = %d",div);
	getch();
	m
      }
